using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Options;
using NotificationsService.Data;
using NotificationsService.Models;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
namespace NotificationsService.Messaging;
public sealed class NotificationEventsConsumer : BackgroundService
{
    private readonly RabbitMqOptions _options; private readonly IServiceScopeFactory _scopeFactory; private readonly ILogger<NotificationEventsConsumer> _logger; private IConnection? _connection; private IChannel? _channel;
    public NotificationEventsConsumer(IOptions<RabbitMqOptions> options, IServiceScopeFactory scopeFactory, ILogger<NotificationEventsConsumer> logger) { _options = options.Value; _scopeFactory = scopeFactory; _logger = logger; }
    protected override async Task ExecuteAsync(CancellationToken stoppingToken) { var factory = new ConnectionFactory { HostName = _options.Host, UserName = _options.Username, Password = _options.Password }; _connection = await factory.CreateConnectionAsync(stoppingToken); _channel = await _connection.CreateChannelAsync(cancellationToken: stoppingToken); await _channel.ExchangeDeclareAsync(_options.ExchangeName, ExchangeType.Topic, durable: true, autoDelete: false, cancellationToken: stoppingToken); await _channel.QueueDeclareAsync("notifications.integration-events", durable: true, exclusive: false, autoDelete: false, cancellationToken: stoppingToken); foreach (var key in new[] { "order.created", "stock.reserved", "stock.rejected", "payment.completed" }) await _channel.QueueBindAsync("notifications.integration-events", _options.ExchangeName, key, cancellationToken: stoppingToken); var consumer = new AsyncEventingBasicConsumer(_channel); consumer.ReceivedAsync += HandleMessageAsync; await _channel.BasicConsumeAsync("notifications.integration-events", false, consumer, stoppingToken); }
    private async Task HandleMessageAsync(object sender, BasicDeliverEventArgs args) { try { var json = Encoding.UTF8.GetString(args.Body.Span); var routingKey = args.RoutingKey; var notification = CreateNotification(routingKey, json); if (notification is null) { await _channel!.BasicNackAsync(args.DeliveryTag, false, false); return; } using var scope = _scopeFactory.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<NotificationsDbContext>(); db.Notifications.Add(notification); await db.SaveChangesAsync(); await _channel!.BasicAckAsync(args.DeliveryTag, false); } catch (Exception ex) { _logger.LogError(ex, "Error processing integration event"); await _channel!.BasicNackAsync(args.DeliveryTag, false, true); } }
    private static Notification? CreateNotification(string routingKey, string json) => routingKey switch { "order.created" => FromOrder(JsonSerializer.Deserialize<OrderCreatedEvent>(json)), "stock.reserved" => FromStockReserved(JsonSerializer.Deserialize<StockReservedEvent>(json)), "stock.rejected" => FromStockRejected(JsonSerializer.Deserialize<StockRejectedEvent>(json)), "payment.completed" => FromPayment(JsonSerializer.Deserialize<PaymentCompletedEvent>(json)), _ => null };
    private static Notification? FromOrder(OrderCreatedEvent? e) => e is null ? null : new Notification { OrderId = e.OrderId, Recipient = e.Customer, Subject = $"Order {e.OrderId} created", Message = $"Order for {e.Quantity} x {e.Product} was created.", Status = "Pending", CreatedAt = DateTime.UtcNow };
    private static Notification? FromStockReserved(StockReservedEvent? e) => e is null ? null : new Notification { OrderId = e.OrderId, Recipient = "operations@enterprise.local", Subject = $"Stock reserved for order {e.OrderId}", Message = $"Reserved {e.Quantity} x {e.Product}.", Status = "Pending", CreatedAt = DateTime.UtcNow };
    private static Notification? FromStockRejected(StockRejectedEvent? e) => e is null ? null : new Notification { OrderId = e.OrderId, Recipient = "operations@enterprise.local", Subject = $"Stock rejected for order {e.OrderId}", Message = e.Reason, Status = "Pending", CreatedAt = DateTime.UtcNow };
    private static Notification? FromPayment(PaymentCompletedEvent? e) => e is null ? null : new Notification { OrderId = e.OrderId, Recipient = "billing@enterprise.local", Subject = $"Payment completed for order {e.OrderId}", Message = $"Payment completed for amount {e.Amount}.", Status = "Pending", CreatedAt = DateTime.UtcNow };
    public override async Task StopAsync(CancellationToken cancellationToken) { if (_channel is not null) await _channel.DisposeAsync(); if (_connection is not null) await _connection.DisposeAsync(); await base.StopAsync(cancellationToken); }
}
